import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import "./globals.css";

// Components
import SessionProvider from "./components/SessionProvider"
import Provider from './Provider';
import Nav from "./components/Nav";

const notoThai = Noto_Sans_Thai({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoThai.className} dark:bg-superdark`}>
        <Provider>
          <Nav/>
          <main className="container pt-20">
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}
